version: '3'
services:
  server:
    build: ./
    ports:
      - '8080:8080'
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: 'redis://redis:6379'
      WINDOW_REDUCE_METHOD: 'buffer'
      OPENAI_API_KEY: <OPENAI_API_KEY>
      RUST_BACKTRACE: 1
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
